### ISSUE TITLE
Change default mountPath of activemq to /opt/activemq/data

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-activemq-deployment#5]
persistence.mountPath is now set to `/data`. Please change it in the values.yaml to the default activemq path `/opt/activemq/data` for the container to use the volume

**Comment by rgauss** [comment]
Indeed it looks like the helm chart still has an old path and it should be updated for the [path in the Alfresco ActiveMQ Dockerfile](https://github.com/Alfresco/alfresco-docker-activemq/blob/master/Dockerfile#L16).

**Comment by melahn** [comment]
Shadowed in https://issues.alfresco.com/jira/browse/DEPLOY-646

**Comment by jottley** [comment]
This issue has now been fixed
